/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package igu.main;

import data.Conn;


import igu.main.CambiaPanel;
import igu.main.Validate;
import igu.User.userPanel;
import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Asullom
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {

        initComponents();
        //Conn.connectSQLite();
        this.setIconImage(new ImageIcon(getClass().getResource("/igu/imgs/img/market.png")).getImage());

        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        this.clientesButton.setSelected(true);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        clientesButton = new igu.util.buttons.ASIconButton();
        clientesButton1 = new igu.util.buttons.ASIconButton();
        clientesButton2 = new igu.util.buttons.ASIconButton();
        pnlCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(239, 238, 244));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(893, 67));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        clientesButton.setBackground(new java.awt.Color(239, 238, 244));
        clientesButton.setForeground(new java.awt.Color(128, 128, 131));
        clientesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/igu/imgs/img/collection.png"))); // NOI18N
        clientesButton.setText("Usuario");
        clientesButton.setColorHover(new java.awt.Color(204, 204, 204));
        clientesButton.setColorNormal(new java.awt.Color(239, 238, 244));
        clientesButton.setColorPressed(new java.awt.Color(204, 204, 204));
        clientesButton.setColorTextHover(new java.awt.Color(128, 128, 131));
        clientesButton.setColorTextNormal(new java.awt.Color(128, 128, 131));
        clientesButton.setColorTextPressed(new java.awt.Color(128, 128, 131));
        clientesButton.setFocusable(false);
        clientesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clientesButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clientesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clientesButtonMousePressed(evt);
            }
        });
        clientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesButtonActionPerformed(evt);
            }
        });

        clientesButton1.setBackground(new java.awt.Color(239, 238, 244));
        clientesButton1.setForeground(new java.awt.Color(128, 128, 131));
        clientesButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/igu/imgs/img/collection.png"))); // NOI18N
        clientesButton1.setText("Cliente");
        clientesButton1.setColorHover(new java.awt.Color(204, 204, 204));
        clientesButton1.setColorNormal(new java.awt.Color(239, 238, 244));
        clientesButton1.setColorPressed(new java.awt.Color(204, 204, 204));
        clientesButton1.setColorTextHover(new java.awt.Color(128, 128, 131));
        clientesButton1.setColorTextNormal(new java.awt.Color(128, 128, 131));
        clientesButton1.setColorTextPressed(new java.awt.Color(128, 128, 131));
        clientesButton1.setFocusable(false);
        clientesButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clientesButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clientesButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clientesButton1MousePressed(evt);
            }
        });
        clientesButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesButton1ActionPerformed(evt);
            }
        });

        clientesButton2.setBackground(new java.awt.Color(239, 238, 244));
        clientesButton2.setForeground(new java.awt.Color(128, 128, 131));
        clientesButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/igu/imgs/img/collection.png"))); // NOI18N
        clientesButton2.setText("Administrador");
        clientesButton2.setColorHover(new java.awt.Color(204, 204, 204));
        clientesButton2.setColorNormal(new java.awt.Color(239, 238, 244));
        clientesButton2.setColorPressed(new java.awt.Color(204, 204, 204));
        clientesButton2.setColorTextHover(new java.awt.Color(128, 128, 131));
        clientesButton2.setColorTextNormal(new java.awt.Color(128, 128, 131));
        clientesButton2.setColorTextPressed(new java.awt.Color(128, 128, 131));
        clientesButton2.setFocusable(false);
        clientesButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clientesButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clientesButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clientesButton2MousePressed(evt);
            }
        });
        clientesButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clientesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(clientesButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(clientesButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(694, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientesButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientesButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(jPanel2, gridBagConstraints);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(pnlPrincipal);

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE)
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(pnlCentro, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed

    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged

    }//GEN-LAST:event_jPanel2MouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void clientesButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesButtonMousePressed
        // TODO add your handling code here:
        this.clientesButton.setSelected(true);
        
    }//GEN-LAST:event_clientesButtonMousePressed

    private void clientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesButtonActionPerformed
        new CambiaPanel(pnlPrincipal, new userPanel());
        /*if (new Validate().comprobar()) {

        } else {
            new CambiaPanel(pnlPrincipal, new PinPanel());
        }*/

        if (this.clientesButton.isSelected()) {
            this.clientesButton.setColorNormal(new Color(204, 204, 204));
            this.clientesButton.setColorHover(new Color(204, 204, 204));
            this.clientesButton.setColorPressed(new Color(204, 204, 204));

           

        } else {
            this.clientesButton.setColorNormal(new Color(239, 238, 244));
            this.clientesButton.setColorHover(new Color(204, 204, 204));
            this.clientesButton.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_clientesButtonActionPerformed

    private void clientesButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesButton1MousePressed
        // TODO add your handling code here:
        this.clientesButton.setSelected(true);
    }//GEN-LAST:event_clientesButton1MousePressed

    private void clientesButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesButton1ActionPerformed
        // TODO add your handling code here:
         new CambiaPanel(pnlPrincipal, new userPanel());
        /*if (new Validate().comprobar()) {

        } else {
            new CambiaPanel(pnlPrincipal, new PinPanel());
        }*/

        if (this.clientesButton.isSelected()) {
            this.clientesButton.setColorNormal(new Color(204, 204, 204));
            this.clientesButton.setColorHover(new Color(204, 204, 204));
            this.clientesButton.setColorPressed(new Color(204, 204, 204));

           

        } else {
            this.clientesButton.setColorNormal(new Color(239, 238, 244));
            this.clientesButton.setColorHover(new Color(204, 204, 204));
            this.clientesButton.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_clientesButton1ActionPerformed

    private void clientesButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesButton2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesButton2MousePressed

    private void clientesButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesButton2ActionPerformed
        // TODO add your handling code here:
         new CambiaPanel(pnlPrincipal, new userPanel());
        /*if (new Validate().comprobar()) {

        } else {
            new CambiaPanel(pnlPrincipal, new PinPanel());
        }*/

        if (this.clientesButton.isSelected()) {
            this.clientesButton.setColorNormal(new Color(204, 204, 204));
            this.clientesButton.setColorHover(new Color(204, 204, 204));
            this.clientesButton.setColorPressed(new Color(204, 204, 204));

           

        } else {
            this.clientesButton.setColorNormal(new Color(239, 238, 244));
            this.clientesButton.setColorHover(new Color(204, 204, 204));
            this.clientesButton.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_clientesButton2ActionPerformed

    /**
     * @param args the command line arguments
     *
     * public static void main(String args[]) { //Create and display the form
     * java.awt.EventQueue.invokeLater(new Runnable() { public void run() { new
     * MainFrame().setVisible(true); } }); }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private igu.util.buttons.ASIconButton clientesButton;
    private igu.util.buttons.ASIconButton clientesButton1;
    private igu.util.buttons.ASIconButton clientesButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCentro;
    public static javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
